# Commands to start on workspace startup
tasks:
  - before: npm i -g pnpm
    init: pnpm install
    command: pnpm start
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
  - port: 8001
    onOpen: open-preview
